name: Deploy to EKS

on:
  workflow_run:
    workflows: ["Provision Infrastructure", "Build and Push Docker Images"] 
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name voting-app-0123 --region ${{ secrets.AWS_REGION }}

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f k8s/.

      - name: Verify all pods are running
        run: |
          kubectl get pods

      - name: Get service details
        run: kubectl get svc -n default
