name: Provisioning Infra - Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=./Terraform init -upgrade

      - name: Terraform Validate
        run: terraform -chdir=./Terraform validate

      - name: Terraform Import Existing IAM Roles
        run: |
          terraform -chdir=./Terraform import aws_iam_role.eks_cluster voting-app-eks-cluster-role || echo "eks_cluster role already imported"
          terraform -chdir=./Terraform import aws_iam_role.eks_nodes voting-app-eks-node-role || echo "eks_nodes role already imported"

      - name: Terraform Plan
        run: terraform -chdir=./Terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply
        run: terraform -chdir=./Terraform apply -auto-approve -var-file=terraform.tfvars

  docker:
    needs: terraform
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        service: [vote, result, worker]  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
      - name: Build and Push ${{ matrix.service }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest ./${{ matrix.service }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
